INSERT INTO CATEGORIE_RECETTE (CTG_NOM_CATEGORIE_RECETTE) VALUES ('Entree');
INSERT INTO CATEGORIE_RECETTE (CTG_NOM_CATEGORIE_RECETTE) VALUES ('Plat');
INSERT INTO CATEGORIE_RECETTE (CTG_NOM_CATEGORIE_RECETTE) VALUES ('Dessert');

SELECT * FROM CATEGORIE_RECETTE;

INSERT INTO RECETTE (CTG_ID,R_NOM_RECETTE,R_DESC_RECETTE,)VALUES (